# https://aka.ms/yaml

trigger:
  - master

variables:
    regression: 1

jobs:
  - job: build_ubuntu_1604
    displayName: Ubuntu 1604
    pool:
      vmImage: 'Ubuntu-16.04'

    strategy:
      matrix:
        avx2:
          SIMD: 'AVX2'
          STATIC: 1
          MPI: 0
        sse:
          SIMD: 'SSE4_1'
          STATIC: 1
          MPI: 0
        avx2_mpi:
          SIMD: 'AVX2'
          STATIC: 0
          MPI: 1

    steps:
      - checkout: self
        submodules: true
      - script: |
          sudo apt-get update
          sudo apt-get -y install mpi-default-dev mpi-default-bin
        displayName: Install Dependencies
        condition: eq(variables['MPI'], 1)
      - script: |
          mkdir build && cd build
          if [ "${STATIC}" -eq "1" ]; then
              cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=OFF \
                -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc \
                -static-libstdc++" -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" \
                -DENABLE_WERROR=1 -DHAVE_${SIMD}=1 -DHAVE_MPI=${MPI} ..
          else
              cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                -DENABLE_WERROR=1 -DHAVE_${SIMD}=1 -DHAVE_MPI=${MPI} ..
          fi

          make -j $(nproc --all)
        displayName: Build MetaEuk
      - script: |
          cd ${BUILD_SOURCESDIRECTORY}/tests
          ./run.sh "${BUILD_SOURCESDIRECTORY}/build/src/whisper"
        displayName: Run Regression Suite
        condition: eq(variables['regression'], 1)
      - task: PublishPipelineArtifact@0
        condition: eq(variables['STATIC'], 1)
        inputs:
          targetPath: $(Build.SourcesDirectory)/build/src/whisper
          artifactName: whisper-linux-$(SIMD)

  - job: build_macos_1014
    displayName: macOS 1014
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - checkout: self
        submodules: true
      - script: |
          brew install cmake gcc@9 zlib bzip2 coreutils
        displayName: Install Dependencies
      - script: |
          cd ${BUILD_SOURCESDIRECTORY}
          CC=gcc-9 CXX=g++-9 ./lib/mmseqs/util/build_osx.sh . build whisper
        displayName: Build MetaEuk
      - script: |
          cd ${BUILD_SOURCESDIRECTORY}/tests
          ./run.sh "${BUILD_SOURCESDIRECTORY}/build/build_sse41/src/whisper"
        displayName: Run Regression Suite
        condition: eq(variables['regression'], 1)
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: $(Build.SourcesDirectory)/build/build_sse41/src/whisper
          artifactName: whisper-darwin-sse41
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: $(Build.SourcesDirectory)/build/build_avx2/src/whisper
          artifactName: whisper-darwin-avx2

  # - job: build_windows_2019
  #   displayName: Windows 2019
  #   pool:
  #     vmImage: 'windows-2019'
  #   variables:
  #     CYGWIN_ROOT: $(System.Workfolder)\cygwin
  #     CYGWIN_MIRROR: http://cygwin.mirror.constant.com
  #   timeoutInMinutes: 120
  #   steps:
  #     - powershell: git config --global core.autocrlf false
  #       displayName: core.autocrlf false
  #     - checkout: self
  #       submodules: true
  #     - script: |
  #         choco install cygwin --params="/InstallDir:%CYGWIN_ROOT%"
  #       displayName: Install Cygwin
  #     - script: |
  #         %CYGWIN_ROOT%\cygwinsetup.exe -qnNdO -R "%CYGWIN_ROOT%" -s "%CYGWIN_MIRROR%" -g -P ^
  #         bash,^
  #         xxd,^
  #         cmake,^
  #         make,^
  #         gcc-core,^
  #         gcc-g++,^
  #         zlib-devel,^
  #         libbz2-devel,^
  #         busybox-standalone,^
  #         git,^
  #         binutils,^
  #         wget,^
  #         perl
  #       displayName: Install Dependencies
  #     - script: |
  #         %CYGWIN_ROOT%\bin\bash.exe -cl "${BUILD_SOURCESDIRECTORY}/lib/mmseqs/util/build_windows.sh $(cygpath ${BUILD_SOURCESDIRECTORY}) $(cygpath ${BUILD_SOURCESDIRECTORY}/build) whisper"
  #       displayName: Build MetaEuk
  #     - task: "ArchiveFiles@2"
  #       inputs:
  #         rootFolderOrFile: $(Build.SourcesDirectory)\build\whisper
  #         archiveFile: $(Build.SourcesDirectory)\whisper-win64.zip
  #         includeRootFolder: true
  #         archiveType: zip
  #     - task: PublishPipelineArtifact@0
  #       inputs:
  #         targetPath: $(Build.SourcesDirectory)\whisper-win64.zip
  #         artifactName: whisper-win64
  #     - script: |
  #         %BUILD_SOURCESDIRECTORY%\build\whisper\whisper.bat version
  #       displayName: Setup Busybox
  #     - script: |
  #         %CYGWIN_ROOT%\bin\bash.exe -cl "cd ${BUILD_SOURCESDIRECTORY}/tests && ./run.sh $(cygpath ${BUILD_SOURCESDIRECTORY}/build/whisper/bin/whisper.exe)"
  #       displayName: Run Regression Suite
  #       condition: eq(variables['regression'], 1)

  - job: upload_artifacts
    displayName: Upload Artifacts
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: 'Ubuntu-16.04'
    dependsOn:
      - build_macos_1014
      - build_ubuntu_1604
      # - build_windows_2019
    steps:
      - script: |
          cd "${BUILD_SOURCESDIRECTORY}"
          mkdir whisper
          cp -f README.md LICENCE.md whisper
          mkdir whisper/bin
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: whisper-darwin-sse41
          targetPath: $(Build.SourcesDirectory)/whisper/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/whisper/bin/whisper"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/whisper
          archiveFile: $(Build.SourcesDirectory)/whisper-osx-sse41.tar.gz
          includeRootFolder: true
          archiveType: tar
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: whisper-darwin-avx2
          targetPath: $(Build.SourcesDirectory)/whisper/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/whisper/bin/whisper"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/whisper
          archiveFile: $(Build.SourcesDirectory)/whisper-osx-avx2.tar.gz
          includeRootFolder: true
          archiveType: tar
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: whisper-linux-SSE4_1
          targetPath: $(Build.SourcesDirectory)/whisper/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/whisper/bin/whisper"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/whisper
          archiveFile: $(Build.SourcesDirectory)/whisper-linux-sse41.tar.gz
          includeRootFolder: true
          archiveType: tar
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: whisper-linux-AVX2
          targetPath: $(Build.SourcesDirectory)/whisper/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/whisper/bin/whisper"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/whisper
          archiveFile: $(Build.SourcesDirectory)/whisper-linux-avx2.tar.gz
          includeRootFolder: true
          archiveType: tar
      - script:
          rm "${BUILD_SOURCESDIRECTORY}/whisper/bin/whisper"
      # - task: DownloadPipelineArtifact@1
      #   inputs:
      #     artifactName: whisper-win64
      #     targetPath: $(Build.SourcesDirectory)
      # - script: |
      #     unzip "${BUILD_SOURCESDIRECTORY}/whisper-win64.zip"
      #     chmod +x whisper/whisper.bat whisper/bin/*
      # - task: ArchiveFiles@2
      #   inputs:
      #     rootFolderOrFile: $(Build.SourcesDirectory)/whisper
      #     archiveFile: $(Build.SourcesDirectory)/whisper-win64.zip
      #     includeRootFolder: true
      #     archiveType: zip
      - task: DownloadSecureFile@1
        inputs:
          secureFile: azure_upload_whisper
        displayName: Get Deployment Key
      - script: |
          mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa uniclust.mmseqs.com >> ~/.ssh/known_hosts
          cd "${BUILD_SOURCESDIRECTORY}"
          ssh codeship@uniclust.mmseqs.com "mkdir -p \"/home/mirdita/repositories/mmseqs-webserver/archive/${BUILD_SOURCEVERSION}\""
          scp whisper-osx-avx2.tar.gz whisper-linux-sse41.tar.gz whisper-linux-avx2.tar.gz codeship@uniclust.mmseqs.com:"/home/mirdita/repositories/mmseqs-webserver/archive/${BUILD_SOURCEVERSION}"
          ssh codeship@uniclust.mmseqs.com "update-latest-whisper.sh \"${BUILD_SOURCEVERSION}\""
